"""ward-core IR v0.1 — the typed intermediate representation for Ward Phase 2.

Design source: files/ward-phase2-scoping.md §4 (ward-core v0.1 calculus sketch,
typing rules T1-T8) and §5 (elaborator pipeline).
Grounding: phase0/grammar/ward0.lark (the ward0 subset) and
phase0/transpiler/transpiler.py (the current syntax-directed pass this IR
formalizes).
"""

from wardcore.ir import (
    Assign,
    Binary,
    Block,
    BoolLit,
    Call,
    CallStmt,
    Contract,
    ContractKind,
    EffectKind,
    Expr,
    ExternFn,
    Function,
    If,
    Indexed,
    IntLit,
    Loop,
    Module,
    Param,
    Quant,
    Return,
    Stmt,
    StrLit,
    TBool,
    TInt,
    TList,
    TResult,
    TStr,
    TUnit,
    Tier,
    Type,
    Unary,
    Var,
    VarDecl,
    validate_module,
)

__all__ = [
    "Assign",
    "Binary",
    "Block",
    "BoolLit",
    "Call",
    "CallStmt",
    "Contract",
    "ContractKind",
    "EffectKind",
    "Expr",
    "ExternFn",
    "Function",
    "If",
    "Indexed",
    "IntLit",
    "Loop",
    "Module",
    "Param",
    "Quant",
    "Return",
    "Stmt",
    "StrLit",
    "TBool",
    "TInt",
    "TList",
    "TResult",
    "TStr",
    "TUnit",
    "Tier",
    "Type",
    "Unary",
    "Var",
    "VarDecl",
    "validate_module",
]
